RepSheet = RepSheet or {}
local ns = RepSheet

ns.UI_FRAME_HEIGHT = 720
ns.UI_PANE_WIDTH = 510
ns.UI_PANE_GAP = 12
ns.UI_FRAME_SIDE_INSET = 18
ns.UI_FRAME_WIDTH = (ns.UI_PANE_WIDTH * 2) + ns.UI_PANE_GAP + (ns.UI_FRAME_SIDE_INSET * 2)
ns.UI_FRAME_TOP_OFFSET = -92
ns.UI_PANE_HEIGHT_TRIM = 124
ns.UI_FRAME_FOOTER_SIDE_INSET = 20
ns.UI_FRAME_FOOTER_BOTTOM_INSET = 18
ns.UI_FRAME_FOOTER_GAP = -14
ns.UI_MAIN_TITLE_LEFT = 20
ns.UI_MAIN_TITLE_TOP = -18
ns.UI_MAIN_SUBTITLE_GAP = -4
ns.UI_MAIN_INFO_LEFT = 22
ns.UI_MAIN_INFO_TOP = -60
ns.UI_CLOSE_BUTTON_RIGHT = -8
ns.UI_CLOSE_BUTTON_TOP = -8
ns.UI_DEBUG_BUTTON_WIDTH = 72
ns.UI_OPTIONS_BUTTON_WIDTH = 84
ns.UI_FORGET_ALT_BUTTON_WIDTH = 96
ns.UI_DEBUG_BUTTON_HEIGHT = 22
ns.UI_DEBUG_BUTTON_GAP = -4
ns.UI_PANE_SCROLL_LEFT = 12
ns.UI_PANE_SCROLL_RIGHT = -28

ns.UI_LIST_ROW_HEIGHT = 66
ns.UI_LIST_MIN_WIDTH = 260
ns.UI_LIST_SCROLL_FALLBACK_HEIGHT = 280
ns.UI_LIST_SCROLL_CHILD_EXTRA_HEIGHT = 8
ns.UI_LIST_SCROLL_CHILD_MIN_HEIGHT = 80
ns.UI_LIST_WHEEL_STEP_ROWS = 2
ns.UI_SEARCH_REFRESH_DELAY_SECONDS = 0.12
ns.UI_LIST_CHILD_X = 4
ns.UI_LIST_CHILD_Y = -2
ns.UI_DROPDOWN_DISABLED_ALPHA = 0.55
ns.UI_DEBUG_SCROLL_STEP = 32
ns.UI_FACTION_TOGGLE_HIT_INSETS = { -6, -6, -5, -5 }
ns.UI_FAVORITE_BUTTON_HIT_INSETS = { -4, -4, -4, -4 }
ns.UI_FAVORITE_TOOLTIP_COLOR = ns.FALLBACK_CLASS_COLOR

ns.UI_DETAIL_ROW_HEIGHT = 34
ns.UI_DETAIL_ROW_WIDTH_TRIM = 8
ns.UI_DETAIL_ROW_INSET_X = 4
ns.UI_DETAIL_ROW_INSET_Y = -2
ns.UI_PROGRESS_BAR_LAYOUT = {
	HORIZONTAL_INSET = 1,
	VERTICAL_INSET = 1,
	STACKED_VERTICAL_INSET = 2,
}

ns.UI_TEXTURES = {
	SOLID = "Interface\\Buttons\\WHITE8X8",
	TOOLTIP_BORDER = "Interface\\Tooltips\\UI-Tooltip-Border",
	DIALOG_BG = "Interface\\DialogFrame\\UI-DialogBox-Background",
	DIALOG_BG_DARK = "Interface\\DialogFrame\\UI-DialogBox-Background-Dark",
	DIALOG_BORDER = "Interface\\DialogFrame\\UI-DialogBox-Border",
	STATUS_BAR = "Interface\\TargetingFrame\\UI-StatusBar",
	MINIMAP_ICON = "Interface\\AddOns\\RepSheet\\Media\\Icons\\RepSheetMinimapIcon",
	MINIMAP_BORDER = "Interface\\Minimap\\MiniMap-TrackingBorder",
	MINIMAP_BACKGROUND = "Interface\\Minimap\\UI-Minimap-Background",
	MINIMAP_HIGHLIGHT = "Interface\\Minimap\\UI-Minimap-ZoomButton-Highlight",
}

ns.UI_MINIMAP_BUTTON_SIZE = 31
ns.UI_MINIMAP_RADIUS_OFFSET = 5
ns.UI_MINIMAP_OVERLAY_SIZE = 50
ns.UI_MINIMAP_BACKGROUND_SIZE = 24
ns.UI_MINIMAP_ICON_SIZE = 18

ns.UI_BACKDROPS = {
	FRAME = {
		bgFile = ns.UI_TEXTURES.DIALOG_BG,
		edgeFile = ns.UI_TEXTURES.DIALOG_BORDER,
		tile = true,
		tileSize = 32,
		edgeSize = 32,
		insets = { left = 10, right = 10, top = 10, bottom = 10 },
	},
	PANE = {
		bgFile = ns.UI_TEXTURES.DIALOG_BG_DARK,
		edgeFile = ns.UI_TEXTURES.TOOLTIP_BORDER,
		tile = true,
		tileSize = 16,
		edgeSize = 12,
		insets = { left = 4, right = 4, top = 4, bottom = 4 },
	},
	ROW = {
		bgFile = ns.UI_TEXTURES.SOLID,
		edgeFile = ns.UI_TEXTURES.TOOLTIP_BORDER,
		tile = true,
		tileSize = 8,
		edgeSize = 10,
		insets = { left = 2, right = 2, top = 2, bottom = 2 },
	},
}

ns.UI_COLORS = {
	FRAME_BG = { 0, 0, 0, 0.96 },
	PANE_BG = { 0.04, 0.04, 0.06, 0.96 },
	PANE_BORDER = { 0.55, 0.44, 0.18, 0.75 },
	ROW_BG = { 0.04, 0.04, 0.06, 0.9 },
	ROW_BORDER = { 0.42, 0.33, 0.16, 0.65 },
	ROW_SELECTED_BG = { 0.18, 0.14, 0.05, 0.96 },
	ROW_SELECTED_BORDER = { 1, 0.82, 0.2, 0.95 },
	DETAIL_ROW_BG = { 0.03, 0.03, 0.05, 0.85 },
	DETAIL_ROW_BORDER = { 0.34, 0.28, 0.16, 0.45 },
	TEXT_TITLE = { 1, 0.9, 0.55 },
	TEXT_TITLE_MUTED = { 1, 0.91, 0.55 },
	TEXT_SUBTITLE = { 0.82, 0.82, 0.88 },
	TEXT_INFO = { 0.72, 0.76, 0.84 },
	TEXT_LABEL = { 0.86, 0.86, 0.86 },
	TEXT_MUTED = { 0.78, 0.78, 0.83 },
	TEXT_STATUS = { 0.62, 0.69, 0.76 },
	TEXT_ACCENT = { 0.9, 0.84, 0.66 },
	TEXT_FOOTER = { 0.7, 0.74, 0.82 },
	TEXT_EMPTY = { 0.8, 0.8, 0.82 },
	FAVORITE_HEART_ACTIVE = { 0.98, 0.38, 0.52 },
	FAVORITE_HEART_INACTIVE = { 0.62, 0.66, 0.74 },
	TOOLTIP_BG = { 0.04, 0.04, 0.06, 1 },
	TOOLTIP_BORDER = { 0.55, 0.44, 0.18, 1 },
	STATUS_BAR_BG = { 0.1, 0.1, 0.12, 0.85 },
	STATUS_BAR_BG_SOLID = { 0.1, 0.1, 0.12, 0.9 },
	STATUS_BAR_DEFAULT = { 0.94, 0.62, 0.18 },
	STATUS_BAR_BAND = { 0.17, 0.58, 0.84 },
	STATUS_BAR_MAXED = { 0.86, 0.69, 0.18 },
	STATUS_BAR_PARAGON = { 0.6, 0.42, 0.88 },
}

ns.UI_MAIN_LAYOUT = {
	SEARCH_LABEL_LEFT = 14,
	SEARCH_LABEL_TOP = -8,
	SEARCH_BOX_WIDTH = 250,
	SEARCH_BOX_HEIGHT = 32,
	SEARCH_BOX_GAP = -3,
	SCAN_BUTTON_WIDTH = 116,
	SCAN_BUTTON_HEIGHT = 24,
	SCAN_BUTTON_RIGHT = -14,
	SCAN_BUTTON_TOP = -22,
	CONTROL_ROW_ONE_TOP = -64,
	CONTROL_ROW_TWO_TOP = -118,
	CONTROL_COL_ONE_LEFT = 14,
	CONTROL_COL_TWO_LEFT = 250,
	DROPDOWN_LEFT_OFFSET = -14,
	DROPDOWN_TOP_OFFSET = -1,
	EXPANSION_DROPDOWN_WIDTH = 190,
	SORT_DROPDOWN_WIDTH = 220,
	STATUS_DROPDOWN_WIDTH = 210,
	COUNT_LEFT = 16,
	COUNT_TOP = -180,
	LIST_SCROLL_LEFT = ns.UI_PANE_SCROLL_LEFT,
	LIST_SCROLL_TOP = -206,
	LIST_SCROLL_RIGHT = ns.UI_PANE_SCROLL_RIGHT,
	LIST_SCROLL_BOTTOM = 14,
}

ns.UI_FACTION_ROW_LAYOUT = {
	OUTER_WIDTH_TRIM = 8,
	OUTER_HEIGHT_TRIM = 4,
	CONTENT_LEFT = 10,
	TREE_INDENT = 14,
	TOGGLE_SIZE = 16,
	TOGGLE_TOP = -8,
	TOGGLE_RESERVED_WIDTH = 18,
	TITLE_RIGHT = -60,
	TITLE_TOP = -6,
	TITLE_RIGHT_TOP = -4,
	META_TOP_GAP = -2,
	BEST_RIGHT = -176,
	BEST_TOP_GAP = -2,
	COVERAGE_RIGHT = -56,
	COVERAGE_TOP = -36,
	COVERAGE_WIDTH = 112,
	PROGRESS_LEFT = 10,
	PROGRESS_RIGHT = -118,
	PROGRESS_BOTTOM = 8,
	PROGRESS_HEIGHT = 8,
	PROGRESS_TEXT_GAP = 8,
	PROGRESS_TEXT_RIGHT = -8,
	FAVORITE_WIDTH = 20,
	FAVORITE_HEIGHT = 20,
	FAVORITE_RIGHT = -8,
	FAVORITE_TOP = -8,
}

ns.UI_CHARACTER_PANE_LAYOUT = {
	PATH_LEFT = 16,
	PATH_TOP = -14,
	PATH_RIGHT = -140,
	PATH_RIGHT_TOP = -12,
	TITLE_GAP = -2,
	TITLE_LEFT = 16,
	TITLE_TOP = -14,
	TITLE_RIGHT = -140,
	TITLE_RIGHT_TOP = -12,
	SUBTITLE_GAP = -4,
	SUMMARY_LEFT = 16,
	SUMMARY_TOP = -76,
	SUMMARY_RIGHT = -16,
	FAVORITE_WIDTH = 96,
	FAVORITE_HEIGHT = 22,
	FAVORITE_RIGHT = -12,
	FAVORITE_TOP = -12,
	DETAILS_WIDTH = 96,
	DETAILS_HEIGHT = 22,
	DETAILS_TOP_GAP = -4,
	NOTE_GAP = -4,
	SCROLL_LEFT = ns.UI_PANE_SCROLL_LEFT,
	SCROLL_TOP = -112,
	SCROLL_RIGHT = ns.UI_PANE_SCROLL_RIGHT,
	SCROLL_BOTTOM = 12,
	EMPTY_LEFT = 16,
	EMPTY_TOP = -24,
	EMPTY_RIGHT = -16,
	SCROLL_CHILD_MIN_HEIGHT = 64,
	SCROLL_CHILD_PADDING = 12,
	SCROLL_CHILD_EMPTY_HEIGHT = 80,
}

ns.UI_DEBUG_PANE_LAYOUT = {
	TITLE_LEFT = 16,
	TITLE_TOP = -14,
	INFO_LEFT = 16,
	INFO_TOP = -40,
	INFO_RIGHT = -16,
	CLEAR_WIDTH = 86,
	CLEAR_HEIGHT = 22,
	CLEAR_RIGHT = -12,
	CLEAR_TOP = -12,
	WIPE_WIDTH = 112,
	WIPE_HEIGHT = 22,
	WIPE_GAP = -6,
	SCAN_WIDTH = 96,
	SCAN_HEIGHT = 22,
	SCAN_GAP = -6,
	SCROLL_LEFT = ns.UI_PANE_SCROLL_LEFT,
	SCROLL_TOP = -82,
	SCROLL_RIGHT = ns.UI_PANE_SCROLL_RIGHT,
	SCROLL_BOTTOM = 12,
	TEXT_LEFT = 8,
	TEXT_TOP = -8,
	TEXT_RIGHT = -8,
	SCROLL_CHILD_MIN_HEIGHT = 64,
	SCROLL_CHILD_PADDING = 16,
}

ns.UI_FORGET_ALT_DIALOG_LAYOUT = {
	WIDTH = 400,
	HEIGHT = 228,
	TITLE_LEFT = 16,
	TITLE_TOP = -14,
	INFO_LEFT = 16,
	INFO_TOP = -42,
	INFO_RIGHT = -16,
	DROPDOWN_LEFT = 16,
	DROPDOWN_TOP = -122,
	DROPDOWN_WIDTH = 220,
	STATUS_LEFT = 16,
	STATUS_TOP = -162,
	STATUS_RIGHT = -16,
	BUTTON_BOTTOM = 16,
	FORGET_WIDTH = 96,
	FORGET_HEIGHT = 22,
	FORGET_RIGHT = -16,
	CANCEL_WIDTH = 96,
	CANCEL_HEIGHT = 22,
	CANCEL_GAP = -6,
}

ns.UI_OPTIONS_LAYOUT = {
	TITLE_LEFT = 16,
	TITLE_TOP = -18,
	SECTION_LEFT = 16,
	SECTION_TOP = -54,
	WARNING_LEFT = 16,
	WARNING_TOP = -82,
	WARNING_RIGHT = -24,
	RADIO_LEFT = 18,
	RADIO_TOP = -124,
	CHECKBOX_GAP = -28,
	PERIODIC_INPUT_GAP = 10,
	PERIODIC_INPUT_WIDTH = 60,
	PERIODIC_INPUT_HEIGHT = 24,
	PERIODIC_SUFFIX_GAP = 8,
}

ns.UI_DETAIL_ROW_LAYOUT = {
	NAME_LEFT = 10,
	NAME_TOP = -6,
	STATUS_RIGHT = -10,
	STATUS_TOP = -6,
	META_GAP = -2,
	META_RIGHT = -10,
	META_TOP = -18,
	PROGRESS_LEFT = 10,
	PROGRESS_RIGHT = -10,
	PROGRESS_BOTTOM = 6,
	PROGRESS_HEIGHT = 8,
}
